// This file is auto-generated by @hey-api/openapi-ts


export const $ISearchResult = {
    required: ['score'],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            nullable: true,
            readOnly: true
        },
        score: {
            type: 'number',
            format: 'float',
            readOnly: true
        },
        values: {
            type: 'object',
            additionalProperties: {
                type: 'string'
            },
            nullable: true,
            readOnly: true
        },
        allValues: {
            type: 'object',
            additionalProperties: {
                type: 'array',
                items: {
                    type: 'string'
                }
            },
            nullable: true,
            readOnly: true
        }
    },
    additionalProperties: false
} as const;